bug fix at startx

diff --git a/scripts/obco b/scripts/obco
--- a/scripts/obco
+++ b/scripts/obco
@@ -6,6 +6,23 @@ colors="${HOME}/.cache/wal/colors.sh"
 newline="
 "
 
+get_args() {
+    while getopts ":chi:o:qrt" opt; do
+        case "$opt" in
+            "r") reload="on";;
+            "?")
+                printf "%s\n" "Invalid option: -$OPTARG" >&2
+                exit 1
+            ;;
+
+            ":")
+                printf "%s\n" "Option -$OPTARG requires an argument." >&2
+                exit 1
+            ;;
+        esac
+    done
+}
+
 out() {
     [[ "$quiet" != "on" ]] && printf "%s\n" "$1" >&2
 }
@@ -41,14 +58,18 @@ build_conf() {
 
 export_colors() {
     printf "%s\n%s" "# Colors generated by obco " "$ob_colors"
-    out "Exported Colors !"
+    out "* Exported Colors !"
 }
 
 reload_openbox() {
     killall -USR2 openbox >&2
+    out "* Reloaded Openbox !"
 }
 
 main() {
+    # get args
+    get_args "$@"
+
     # Build colors
     build_conf
 
@@ -56,8 +77,7 @@ main() {
     export_colors > "${target}"
 
     # Reload !
-    reload_openbox
+    [[ "$reload" == "on" ]] && reload_openbox
 }
 
-main
-
+main "$@"
diff --git a/scripts/wal-set b/scripts/wal-set
--- a/scripts/wal-set
+++ b/scripts/wal-set
@@ -1,39 +1,49 @@
-#!/usr/bin/env bash
-#
+#!/bin/bash
+
 # Script to set colors generated by 'wal'
 # https://github.com/dylanaraps/wal
 
 # Source generated colors.
 source "${HOME}/.cache/wal/colors.sh"
 
-reload_dunst() {
-    pkill dunst && \
-        dunst \
-            -lb "$color15" \
-            -nb "$color15" \
-            -cb "$color15" \
-            -lf "$color0"  \
-            -bf "$color0"  \
-            -cf "$color9" &
-}
+get_args() { # {{{
+    while getopts ":chi:o:qrt" opt; do
+        case "$opt" in
+            "r") reload="off";;
+            "?")
+                printf "%s\n" "Invalid option: -$OPTARG" >&2
+                exit 1
+            ;;
+            ":")
+                printf "%s\n" "Option -$OPTARG requires an argument." >&2
+                exit 1
+            ;;
+        esac
+    done
+} #}}}
 
-set_bar() {
+set_bar() { # {{{
     pkill bar
-    bar "$color15" "$color0" #2>/dev/null &
-}
+    bar "$color15" "$color0" 2>/dev/null &
+} # }}}
 
-set_scss() {
-    sassc --style expanded "$HOME/projects/startpage/scss/style.scss" > "$HOME/projects/startpage/style.css"
-}
+set_openbox() { #{{{
+    obco
+} #}}}
 
-set_openbox() {
-    obco >&2
-}
+reload_openbox() { # {{{
+    echo "* Reloading Openbox"
+    killall -USR2 openbox >&2
+} # }}}
 
-main() {
-    reload_dunst &
+main() { # {{{
+    get_args "$@"
+
     set_bar &
-    set_openbox &
-}
+    
+    set_openbox
 
-main >/dev/null 2>&1
+    [[ "$reload" != "off" ]] &&  reload_openbox
+} #}}}
+
+main "$@"
